const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const trMonths=['Oca','Şub','Mar','Nis','May','Haz','Tem','Ağu','Eyl','Eki','Kas','Ara'];
const trDays=['Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi','Pazar'];
let cfg={}, students=[], lessons=[], planned=[], currentWeek=monday(new Date());
function money(x){return `${Math.round(Number(x||0)).toLocaleString('tr-TR')} TL`}
function iso(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function monthKey(d=new Date()){return d.toISOString().slice(0,7)}
function monday(d){d=new Date(d); d.setHours(0,0,0,0); d.setDate(d.getDate()-((d.getDay()+6)%7)); return d}
function fmtDate(s){if(!s) return ''; const d=new Date(s+'T00:00'); return `${String(d.getDate()).padStart(2,'0')} ${trMonths[d.getMonth()]} ${['Paz','Pzt','Sal','Çar','Per','Cum','Cmt'][d.getDay()]}`}
function getConfig(){try{return JSON.parse(localStorage.getItem('slm_supabase')||'{}')}catch{return {}}}
function setConfig(c){localStorage.setItem('slm_supabase',JSON.stringify(c))}
async function api(table, opts={}){if(!cfg.url||!cfg.key) throw new Error('Supabase ayarı eksik'); const url=new URL(`${cfg.url.replace(/\/$/,'')}/rest/v1/${table}`); if(opts.query) Object.entries(opts.query).forEach(([k,v])=>url.searchParams.set(k,v)); const res=await fetch(url,{method:opts.method||'GET',headers:{apikey:cfg.key,Authorization:`Bearer ${cfg.key}`,'Content-Type':'application/json',Prefer: opts.prefer||'return=representation'},body:opts.body?JSON.stringify(opts.body):undefined}); if(!res.ok){throw new Error(await res.text())} if(res.status===204) return null; return await res.json()}
function student(id){return students.find(s=>String(s.id)===String(id))||{}}
function studentFee(s){return Number(s.fee || s.hourly_fee || 0)}
function studentCourse(s){return s.subject || s.course || ''}
function studentColor(s){return s.color || '#2563eb'}
async function loadAll(){cfg=getConfig(); if(!cfg.url||!cfg.key){$('#setup').classList.remove('hidden'); return} $('#setup').classList.add('hidden'); try{students=await api('students',{query:{select:'*',order:'id.asc'}}); lessons=await api('lessons',{query:{select:'*',order:'lesson_date.desc,lesson_time.desc'}}); planned=await api('planned',{query:{select:'*',order:'lesson_date.asc,lesson_time.asc'}}); renderAll()}catch(e){alert('Veri okunamadı: '+e.message); $('#setup').classList.remove('hidden')}}
function renderAll(){fillStudentSelects(); renderDashboard(); renderStudents(); renderCalendar(); renderLessons(); renderReport()}
function fillStudentSelects(){const opts=['<option value="">Öğrenci seçin</option>'].concat(students.map(s=>`<option value="${s.id}">${s.name}</option>`)).join(''); ['#dlgStudent','#planStudent'].forEach(id=>$(id).innerHTML=opts); ['#lessonStudentFilter','#reportStudentFilter'].forEach(id=>$(id).innerHTML='<option value="">Tümü</option>'+students.map(s=>`<option value="${s.id}">${s.name}</option>`).join(''))}
function renderDashboard(){const today=iso(new Date()), mk=monthKey(); const todayPlans=planned.filter(p=>p.lesson_date===today && (p.status||'planned')==='planned'); const monthLessons=lessons.filter(l=>(l.lesson_date||'').startsWith(mk)); const income=monthLessons.reduce((a,l)=>a+Number(l.fee||0),0); const unpaid=monthLessons.filter(l=>!l.paid).reduce((a,l)=>a+Number(l.fee||0),0); $('#todayCount').textContent=todayPlans.length; $('#monthCount').textContent=monthLessons.length; $('#monthIncome').textContent=money(income); $('#unpaidIncome').textContent=money(unpaid); renderList('#todayPlan', todayPlans.map(p=>({kind:'plan',...p})), 'Bugün planlanan ders yok.'); renderList('#recentLessons', lessons.slice(0,8).map(l=>({kind:'lesson',...l})), 'Henüz ders yok.')}
function renderList(sel, rows, empty){const el=$(sel); if(!rows.length){el.className='list empty'; el.textContent=empty; return} el.className='list'; el.innerHTML=rows.map(r=>{const s=student(r.student_id), isLesson=r.kind==='lesson'; return `<div class="item"><span class="dot" style="color:${studentColor(s)};background:${studentColor(s)}"></span><div><b>${s.name||'Öğrenci'}</b><small>${fmtDate(r.lesson_date)} ${r.lesson_time||''} ${isLesson?'· '+(r.topic||r.notes||studentCourse(s)||''): '· '+(r.note||studentCourse(s)||'')}</small></div><span class="money">${money(r.fee||studentFee(s))}</span>${isLesson?`<span class="pill ${r.paid?'paid':''}">${r.paid?'Ödendi':'Bekliyor'}</span>`:'<span class="pill paid">Plan</span>'}</div>`}).join('')}
function renderStudents(){const tbody=$('#studentsTable tbody'); tbody.innerHTML=students.map(s=>`<tr data-id="${s.id}"><td>${s.id}</td><td><b>${s.name}</b></td><td>${s.school||''}</td><td>${studentCourse(s)||''}</td><td>${money(studentFee(s))}</td><td>${s.parent_name||''}</td><td>${s.phone||''}</td></tr>`).join(''); tbody.querySelectorAll('tr').forEach(tr=>tr.onclick=()=>editStudent(tr.dataset.id))}
function editStudent(id){const s=student(id); $('#stId').value=s.id; $('#stName').value=s.name||''; $('#stSchool').value=s.school||''; $('#stCourse').value=studentCourse(s)||''; $('#stFee').value=studentFee(s)||''; $('#stParent').value=s.parent_name||''; $('#stPhone').value=s.phone||''; $('#stEmail').value=s.email||''; $('#stColor').value=studentColor(s); $('#stNotes').value=s.notes||''; showPage('students')}
function clearStudentForm(){$$('#stId,#stName,#stSchool,#stCourse,#stFee,#stParent,#stPhone,#stEmail,#stNotes').forEach(x=>x.value=''); $('#stColor').value='#2563eb'}
async function saveStudent(){const id=$('#stId').value; const body={name:$('#stName').value.trim(),school:$('#stSchool').value.trim(),subject:$('#stCourse').value.trim(),course:$('#stCourse').value.trim(),fee:Number($('#stFee').value||0),hourly_fee:Number($('#stFee').value||0),parent_name:$('#stParent').value.trim(),phone:$('#stPhone').value.trim(),email:$('#stEmail').value.trim(),color:$('#stColor').value,notes:$('#stNotes').value.trim(),active:true}; if(!body.name) return alert('Öğrenci adı gerekli.'); if(id){await api('students',{method:'PATCH',query:{id:`eq.${id}`},body})}else{await api('students',{method:'POST',body})} clearStudentForm(); await loadAll()}
function renderCalendar(){const start=new Date(currentWeek), end=new Date(start); end.setDate(start.getDate()+6); $('#weekTitle').textContent=`${fmtDate(iso(start))} - ${fmtDate(iso(end))}`; const hours=Array.from({length:15},(_,i)=>8+i); let html='<div class="cell headCell"></div>'; for(let i=0;i<7;i++){const d=new Date(start);d.setDate(start.getDate()+i); html+=`<div class="cell headCell">${trDays[i]}<br><small>${fmtDate(iso(d))}</small></div>`} for(const h of hours){html+=`<div class="cell timeCell">${String(h).padStart(2,'0')}:00</div>`; for(let i=0;i<7;i++){const d=new Date(start);d.setDate(start.getDate()+i); const day=iso(d); const items=[...planned.filter(p=>p.lesson_date===day && Number((p.lesson_time||'0').slice(0,2))===h).map(p=>({type:'plan',...p})),...lessons.filter(l=>l.lesson_date===day && Number((l.lesson_time||'0').slice(0,2))===h).map(l=>({type:'done',...l}))]; html+=`<div class="cell">${items.map(r=>{const s=student(r.student_id);return `<div class="event ${r.type==='done'?'done':''}" style="border-left-color:${studentColor(s)}"><b>${r.lesson_time||''} ${s.name||''}</b>${r.note||r.topic||studentCourse(s)||''}<br>${money(r.fee||studentFee(s))}</div>`}).join('')}</div>`}} $('#weekGrid').innerHTML=html}
function rowsFiltered(which='lessons'){let arr=lessons; const month=$(which==='report'?'#reportMonth':'#lessonMonth').value; const sid=$(which==='report'?'#reportStudentFilter':'#lessonStudentFilter').value; const paid=$(which==='report'?'#reportPaidFilter':'#lessonPaidFilter').value; if(month) arr=arr.filter(l=>(l.lesson_date||'').startsWith(month)); if(sid) arr=arr.filter(l=>String(l.student_id)===String(sid)); if(paid) arr=arr.filter(l=>String(Boolean(l.paid))===paid); return arr}
function renderLessons(){const rows=rowsFiltered('lessons'); const total=rows.reduce((a,l)=>a+Number(l.fee||0),0), paid=rows.filter(l=>l.paid).reduce((a,l)=>a+Number(l.fee||0),0), unpaid=total-paid; $('#lessonSummary').textContent=`Toplam: ${money(total)}   Ödenen: ${money(paid)}   Bekleyen: ${money(unpaid)}   Ders: ${rows.length}`; fillLessonTable('#lessonsTable tbody', rows)}
function renderReport(){const rows=rowsFiltered('report'); const total=rows.reduce((a,l)=>a+Number(l.fee||0),0), paid=rows.filter(l=>l.paid).reduce((a,l)=>a+Number(l.fee||0),0), unpaid=total-paid; $('#reportSummary').textContent=`Toplam: ${money(total)}   Ödenen: ${money(paid)}   Bekleyen/Planlı: ${money(unpaid)}   Ders: ${rows.length}`; fillLessonTable('#reportTable tbody', rows)}
function fillLessonTable(sel, rows){$(sel).innerHTML=rows.map(l=>{const s=student(l.student_id); return `<tr><td>${fmtDate(l.lesson_date)}</td><td>${l.lesson_time||''}</td><td>${s.name||''}</td><td>${s.school||''}</td><td>${studentCourse(s)||''}</td><td>${l.topic||l.notes||''}</td><td>${money(l.fee)}</td><td><button class="pill ${l.paid?'paid':''}" data-paid="${l.id}">${l.paid?'Ödendi':'Bekliyor'}</button></td></tr>`}).join(''); $$(sel+' [data-paid]').forEach(b=>b.onclick=async()=>{const l=lessons.find(x=>String(x.id)===String(b.dataset.paid)); await api('lessons',{method:'PATCH',query:{id:`eq.${l.id}`},body:{paid:!l.paid}}); await loadAll()})}
function openLessonDialog(){const now=new Date(); $('#dlgDate').value=iso(now); $('#dlgTime').value='18:00'; $('#dlgTopic').value=''; $('#dlgFee').value=''; $('#lessonDialog').showModal()}
function openPlanDialog(){const now=new Date(); $('#planDate').value=iso(now); $('#planTime').value='18:00'; $('#planNote').value=''; $('#planFee').value=''; $('#planDialog').showModal()}
async function saveLesson(ev){ev.preventDefault(); const sid=$('#dlgStudent').value; if(!sid) return alert('Öğrenci seçmelisin.'); const s=student(sid); const body={student_id:Number(sid),lesson_date:$('#dlgDate').value,lesson_time:$('#dlgTime').value,duration:90,duration_min:90,topic:$('#dlgTopic').value,notes:$('#dlgTopic').value,fee:Number($('#dlgFee').value||studentFee(s)||0),paid:false}; await api('lessons',{method:'POST',body}); $('#lessonDialog').close(); await loadAll()}
async function savePlan(ev){ev.preventDefault(); const sid=$('#planStudent').value; if(!sid) return alert('Öğrenci seçmelisin.'); const s=student(sid); const body={student_id:Number(sid),lesson_date:$('#planDate').value,lesson_time:$('#planTime').value,note:$('#planNote').value,fee:Number($('#planFee').value||studentFee(s)||0),status:'planned',repeat_rule:'none',recurring:false}; await api('planned',{method:'POST',body}); $('#planDialog').close(); await loadAll()}
function showPage(p){$$('.page').forEach(x=>x.classList.remove('active')); $('#'+p).classList.add('active'); $$('.nav').forEach(n=>n.classList.toggle('active', n.dataset.page===p))}
function exportCsv(){const rows=rowsFiltered('report'); const csv=[['Tarih','Saat','Öğrenci','Okul','Ders','Konu','Tutar','Durum']].concat(rows.map(l=>{const s=student(l.student_id);return [l.lesson_date,l.lesson_time,s.name||'',s.school||'',studentCourse(s)||'',l.topic||l.notes||'',l.fee,l.paid?'Ödendi':'Bekliyor']})).map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); a.download='ders_raporu.csv'; a.click()}
function bind(){cfg=getConfig(); $('#supabaseUrl').value=cfg.url||''; $('#supabaseKey').value=cfg.key||''; $('#saveConfig').onclick=()=>{setConfig({url:$('#supabaseUrl').value.trim(),key:$('#supabaseKey').value.trim()}); loadAll()}; $('#resetConfig').onclick=()=>{localStorage.removeItem('slm_supabase'); location.reload()}; $$('.nav').forEach(n=>n.onclick=()=>showPage(n.dataset.page)); $('#refresh').onclick=loadAll; ['#quickNew','#newLessonBtn'].forEach(id=>$(id).onclick=openLessonDialog); $('#newPlanBtn').onclick=openPlanDialog; $('#saveLessonDlg').onclick=saveLesson; $('#savePlanDlg').onclick=savePlan; $('#saveStudent').onclick=saveStudent; $('#clearStudent').onclick=clearStudentForm; $('#newStudentBtn').onclick=clearStudentForm; $('#prevWeek').onclick=()=>{currentWeek.setDate(currentWeek.getDate()-7);renderCalendar()}; $('#nextWeek').onclick=()=>{currentWeek.setDate(currentWeek.getDate()+7);renderCalendar()}; $('#thisWeek').onclick=()=>{currentWeek=monday(new Date());renderCalendar()}; ['#lessonMonth','#lessonStudentFilter','#lessonPaidFilter'].forEach(id=>$(id).onchange=renderLessons); ['#reportMonth','#reportStudentFilter','#reportPaidFilter'].forEach(id=>$(id).onchange=renderReport); $('#exportCsv').onclick=exportCsv; $('#lessonMonth').value=monthKey(); $('#reportMonth').value=monthKey()}
bind(); loadAll();
